name: CI

on: [push]

env:
    PORT: 8001
    DATABASE_URL: 'postgresql://prisma:prisma@localhost:5433/tests'
    JWT_ACCESS_EXPIRES_IN: '1h'
    JWT_REFRESH_EXPIRES_IN: '1h'
    JWT_SECRET: 'test'

jobs:
    build:
        name: Node
        runs-on: ubuntu-latest

        env:
            PORT: 8001
            DATABASE_URL: 'postgresql://prisma:prisma@localhost:5433/tests'

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'yarn'

            - name: Intall Dependencies
              run: yarn install

            - name: Run Tests With Coverage
              run: yarn test:coverage

            - name: Upload Test Coverage
              uses: codecov/codecov-action@v3
              with:
                  directory: './coverage'
