name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Node
        runs-on: ubuntu-latest

        env:
            PORT: 8001
            DATABASE_URL: 'postgresql://prisma:prisma@localhost:5433/tests'

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'yarn'

            - name: Intall Dependencies
              run: yarn install

            - name: Run Unit Tests
              run: yarn test:unit

            - name: 'Grant Execution Permissions To wait-for-it'
              run: 'chmod +x ${PWD}/wait-for-it.sh'

            - name: 'Startup Docker'
              run: 'yarn docker:up'

            - name: 'Check Running Containers'
              run: 'docker ps -a'

            - name: Run Integration Tests
              run: yarn test:integration
